<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content=" Плотность и условные обозначения основных элементов в марках металлов и сплавов">
    <meta name="keywords" content=" Плотность , условные обозначения,  элемент, марки металлов , сплавы"
	купить в Киеве , медь, латунь, бронза, припой ПОС, алюминий, свинец, цинк, олово, никель, баббит">
    <meta name="robots" content="index, follow">
    <meta name="author" content="Super Marta">
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="carusel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="carusel/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="style1.css">
    <title>ОСНОВНЫЕ | ЭЛЕМЕНТЫ</title>
</head>
<?php require_once 'header.php'?>
    <div id="main">
        <div class="content" style="text-align: center">
            <div style="overflow: auto;">

                <table style="width: 650px; height: 1282px; margin: 20px auto;" border="0" cellpadding="0" cellspacing="0" align="center">
                    <tbody>
                    <tr>
                        <td class="content"><br />
                            <div align="center"><b> Плотность и условные обозначения основных элементов в марках металлов и сплавов</b>
                                <div>
                                    <table style="width: 100%;" class="mainsmall" border="1">
                                        <tbody>
                                        <tr>
                                            <td><b>Элемент</b></td>
                                            <td><b>Символ</b></td>
                                            <td><b>Черные<br /> металлы</b></td>
                                            <td><b>Цветные<br /> металлы</b></td>
                                            <td><b>Плотность<br /> г/куб.см.</b></td>
                                        </tr>
                                        <tr>
                                            <td>Азот</td>
                                            <td>N</td>
                                            <td>A</td>
                                            <td>.</td>
                                            <td>1,25</td>
                                        </tr>
                                        <tr>
                                            <td>Алюминий</td>
                                            <td>Al</td>
                                            <td>Ю</td>
                                            <td>A</td>
                                            <td>2,69808</td>
                                        </tr>
                                        <tr>
                                            <td>Барий</td>
                                            <td>Ba</td>
                                            <td>.</td>
                                            <td>Бр</td>
                                            <td>3,61</td>
                                        </tr>
                                        <tr>
                                            <td>Бериллий</td>
                                            <td>Be</td>
                                            <td>Л</td>
                                            <td>.</td>
                                            <td>1,86</td>
                                        </tr>
                                        <tr>
                                            <td>Бор</td>
                                            <td>В</td>
                                            <td>Р</td>
                                            <td>.</td>
                                            <td>2,33</td>
                                        </tr>
                                        <tr>
                                            <td>Ванадий</td>
                                            <td>V</td>
                                            <td>Ф</td>
                                            <td>Вам</td>
                                            <td>6,12</td>
                                        </tr>
                                        <tr>
                                            <td>Висмут</td>
                                            <td>Bi</td>
                                            <td>Ви</td>
                                            <td>Ви</td>
                                            <td>9,79</td>
                                        </tr>
                                        <tr>
                                            <td>Вольфрам</td>
                                            <td>W</td>
                                            <td>В</td>
                                            <td>.</td>
                                            <td>19,27</td>
                                        </tr>
                                        <tr>
                                            <td>Гадолиний</td>
                                            <td>Gg</td>
                                            <td>.</td>
                                            <td>Гм</td>
                                            <td>7,886</td>
                                        </tr>
                                        <tr>
                                            <td>Галлий</td>
                                            <td>Ga</td>
                                            <td>Гл</td>
                                            <td>Гл</td>
                                            <td>5,91</td>
                                        </tr>
                                        <tr>
                                            <td>Гафний</td>
                                            <td>Hf</td>
                                            <td>.</td>
                                            <td>Гф</td>
                                            <td>13,36</td>
                                        </tr>
                                        <tr>
                                            <td>Германий</td>
                                            <td>Ge</td>
                                            <td>.</td>
                                            <td>Г</td>
                                            <td>19,3</td>
                                        </tr>
                                        <tr>
                                            <td>Гольмий</td>
                                            <td>Но</td>
                                            <td>.</td>
                                            <td>ГОМ</td>
                                            <td>8,799</td>
                                        </tr>
                                        <tr>
                                            <td>Диспрозий</td>
                                            <td>Dy</td>
                                            <td>.</td>
                                            <td>ДИМ</td>
                                            <td>8,559</td>
                                        </tr>
                                        <tr>
                                            <td>Европий</td>
                                            <td>Eu</td>
                                            <td>.</td>
                                            <td>Eu</td>
                                            <td>5,24</td>
                                        </tr>
                                        <tr>
                                            <td>Железо</td>
                                            <td>Fe</td>
                                            <td>.</td>
                                            <td>Ж</td>
                                            <td>7,87</td>
                                        </tr>
                                        <tr>
                                            <td>Золото</td>
                                            <td>Au</td>
                                            <td>.</td>
                                            <td>Зл</td>
                                            <td>19,32</td>
                                        </tr>
                                        <tr>
                                            <td>Индий</td>
                                            <td>In</td>
                                            <td>.</td>
                                            <td>Ин</td>
                                            <td>7,3</td>
                                        </tr>
                                        <tr>
                                            <td>Иридий</td>
                                            <td>lr</td>
                                            <td>и</td>
                                            <td>И</td>
                                            <td>22,4</td>
                                        </tr>
                                        <tr>
                                            <td>Иттербий</td>
                                            <td>Yb</td>
                                            <td>.</td>
                                            <td>ИТМ</td>
                                            <td>6,959</td>
                                        </tr>
                                        <tr>
                                            <td>Иттрий</td>
                                            <td>Y</td>
                                            <td>.</td>
                                            <td>ИМ</td>
                                            <td>4,472</td>
                                        </tr>
                                        <tr>
                                            <td>Кадмий</td>
                                            <td>Cd</td>
                                            <td>Кд</td>
                                            <td>Кд</td>
                                            <td>8,642</td>
                                        </tr>
                                        <tr>
                                            <td>Кобальт</td>
                                            <td>Co</td>
                                            <td>К</td>
                                            <td>К</td>
                                            <td>8,85</td>
                                        </tr>
                                        <tr>
                                            <td>Кремний</td>
                                            <td>Si</td>
                                            <td>С</td>
                                            <td>Кр</td>
                                            <td>2,3263</td>
                                        </tr>
                                        <tr>
                                            <td>Лантан</td>
                                            <td>La</td>
                                            <td>.</td>
                                            <td>Ла</td>
                                            <td>6,162</td>
                                        </tr>
                                        <tr>
                                            <td>Литий</td>
                                            <td>Li</td>
                                            <td>.</td>
                                            <td>Лэ</td>
                                            <td>0,534</td>
                                        </tr>
                                        <tr>
                                            <td>Лютеций</td>
                                            <td>Lu</td>
                                            <td>.</td>
                                            <td>Люм</td>
                                            <td>.</td>
                                        </tr>
                                        <tr>
                                            <td>Магний</td>
                                            <td>Mg</td>
                                            <td>Ш</td>
                                            <td>Мг</td>
                                            <td>1,741</td>
                                        </tr>
                                        <tr>
                                            <td>Марганец</td>
                                            <td>Mn</td>
                                            <td>Г</td>
                                            <td>Мц(Мр)</td>
                                            <td>7,43</td>
                                        </tr>
                                        <tr>
                                            <td>Медь</td>
                                            <td>Cu</td>
                                            <td>Д</td>
                                            <td>М</td>
                                            <td>8,96</td>
                                        </tr>
                                        <tr>
                                            <td>Молибден</td>
                                            <td>Mo</td>
                                            <td>М</td>
                                            <td>.</td>
                                            <td>10,22</td>
                                        </tr>
                                        <tr>
                                            <td>Мышьяк</td>
                                            <td>As</td>
                                            <td>-</td>
                                            <td>-</td>
                                            <td>-</td>
                                        </tr>
                                        <tr>
                                            <td>Неодим</td>
                                            <td>Nd</td>
                                            <td>.</td>
                                            <td>Нм</td>
                                            <td>7,007</td>
                                        </tr>
                                        <tr>
                                            <td>Никель</td>
                                            <td>Ni</td>
                                            <td>Н</td>
                                            <td>Н</td>
                                            <td>8,91</td>
                                        </tr>
                                        <tr>
                                            <td>Ниобий</td>
                                            <td>Nb</td>
                                            <td>Б</td>
                                            <td>Нп</td>
                                            <td>8,55</td>
                                        </tr>
                                        <tr>
                                            <td>Олово</td>
                                            <td>Sn</td>
                                            <td>.</td>
                                            <td>О</td>
                                            <td>7,29</td>
                                        </tr>
                                        <tr>
                                            <td>Осмий</td>
                                            <td>Os</td>
                                            <td>.</td>
                                            <td>Ос</td>
                                            <td>22,48</td>
                                        </tr>
                                        <tr>
                                            <td>Палладий</td>
                                            <td>Pd</td>
                                            <td>.</td>
                                            <td>Пд</td>
                                            <td>12,1</td>
                                        </tr>
                                        <tr>
                                            <td>Платина</td>
                                            <td>Pt</td>
                                            <td>.</td>
                                            <td>Пл</td>
                                            <td>21</td>
                                        </tr>
                                        <tr>
                                            <td>Празеодим</td>
                                            <td>Pr</td>
                                            <td>.</td>
                                            <td>Пр</td>
                                            <td>6,769</td>
                                        </tr>
                                        <tr>
                                            <td>Рений</td>
                                            <td>Re</td>
                                            <td>.</td>
                                            <td>Ре</td>
                                            <td>21,04</td>
                                        </tr>
                                        <tr>
                                            <td>Родий</td>
                                            <td>Rh</td>
                                            <td>.</td>
                                            <td>Рд</td>
                                            <td>12,5</td>
                                        </tr>
                                        <tr>
                                            <td>Ртуть</td>
                                            <td>Hg</td>
                                            <td>.</td>
                                            <td>Р</td>
                                            <td>13,5</td>
                                        </tr>
                                        <tr>
                                            <td>Рутений</td>
                                            <td>Ru</td>
                                            <td>.</td>
                                            <td>Ру</td>
                                            <td>12,3</td>
                                        </tr>
                                        <tr>
                                            <td>Самарий</td>
                                            <td>Sm</td>
                                            <td>.</td>
                                            <td>Сам</td>
                                            <td>7,53</td>
                                        </tr>
                                        <tr>
                                            <td>Свинец</td>
                                            <td>Pb</td>
                                            <td>.</td>
                                            <td>С</td>
                                            <td>11,337</td>
                                        </tr>
                                        <tr>
                                            <td>Селен</td>
                                            <td>Se</td>
                                            <td>Е</td>
                                            <td>СТ</td>
                                            <td>4,7924</td>
                                        </tr>
                                        <tr>
                                            <td>Сера</td>
                                            <td>S</td>
                                            <td>-</td>
                                            <td>-</td>
                                            <td>-</td>
                                        </tr>
                                        <tr>
                                            <td>Серебро</td>
                                            <td>Ag</td>
                                            <td>.</td>
                                            <td>Ср</td>
                                            <td>10,5</td>
                                        </tr>
                                        <tr>
                                            <td>Скандий</td>
                                            <td>Sc</td>
                                            <td>.</td>
                                            <td>Скм</td>
                                            <td>2,99</td>
                                        </tr>
                                        <tr>
                                            <td>Сурьма</td>
                                            <td>Sb</td>
                                            <td>.</td>
                                            <td>Су</td>
                                            <td>6,69</td>
                                        </tr>
                                        <tr>
                                            <td>Таллий</td>
                                            <td>Tl</td>
                                            <td>.</td>
                                            <td>Тл</td>
                                            <td>11,85</td>
                                        </tr>
                                        <tr>
                                            <td>Тантал</td>
                                            <td>Та</td>
                                            <td>.</td>
                                            <td>ТТ</td>
                                            <td>16,6</td>
                                        </tr>
                                        <tr>
                                            <td>Теллур</td>
                                            <td>Те</td>
                                            <td>.</td>
                                            <td>Т</td>
                                            <td>6,25</td>
                                        </tr>
                                        <tr>
                                            <td>Тербий</td>
                                            <td>Tb</td>
                                            <td>.</td>
                                            <td>Том</td>
                                            <td>8,253</td>
                                        </tr>
                                        <tr>
                                            <td>Титан</td>
                                            <td>Ti</td>
                                            <td>Т</td>
                                            <td>ТПД</td>
                                            <td>4,505</td>
                                        </tr>
                                        <tr>
                                            <td>Тулий</td>
                                            <td>Tu</td>
                                            <td>.</td>
                                            <td>ТУМ</td>
                                            <td>9,318</td>
                                        </tr>
                                        <tr>
                                            <td>Углерод</td>
                                            <td>С</td>
                                            <td>У</td>
                                            <td>.</td>
                                            <td>2,2</td>
                                        </tr>
                                        <tr>
                                            <td>Фосфор</td>
                                            <td>P</td>
                                            <td>П</td>
                                            <td>Ф</td>
                                            <td>1,83</td>
                                        </tr>
                                        <tr>
                                            <td>Хром</td>
                                            <td>Cr</td>
                                            <td>Х</td>
                                            <td>Х(Хр)</td>
                                            <td>7,2</td>
                                        </tr>
                                        <tr>
                                            <td>Церий</td>
                                            <td>Ce</td>
                                            <td>.</td>
                                            <td>Се</td>
                                            <td>6,768</td>
                                        </tr>
                                        <tr>
                                            <td>Цинк</td>
                                            <td>Zn</td>
                                            <td>.</td>
                                            <td>Ц</td>
                                            <td>7,13</td>
                                        </tr>
                                        <tr>
                                            <td>Цирконий</td>
                                            <td>Zr</td>
                                            <td>Ц</td>
                                            <td>ЦЭВ</td>
                                            <td>6,5</td>
                                        </tr>
                                        <tr>
                                            <td>Эрбий</td>
                                            <td>Er</td>
                                            <td>.</td>
                                            <td>ЭРМ</td>
                                            <td>9,062</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </td>
                        <td class="r-column"></td>
                    </tr>
                    </tbody>
                </table>
            </div>



        </div>
    </div>
<?php require_once 'footer.php'?>